apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-vinny-dev-br
  namespace: whoami
spec:
  secretName: k3s-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - whoami.vinny.dev.br
