apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-k3s-vinny-dev-br
  namespace: argocd
spec:
  secretName: argocd-k3s-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - argocd-k3s.vinny.dev.br
