deployment:
  kind: DaemonSet

service:
  type: LoadBalancer

ports:
  web:
    hostPort: 80
  websecure:
    hostPort: 443
  minecraft:
    port: 25565
    expose:
      default: true
    hostPort: 25565
    protocol: TCP

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: true

logs:
  general:
    level: INFO
