deployment:
  kind: DaemonSet

service:
  type: LoadBalancer

ports:
  web:
    hostPort: 80
  websecure:
    hostPort: 443

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: true

logs:
  general:
    level: INFO
