apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-pod-identity-webhook
  namespace: kube-system
spec:
  activeDeadlineSeconds: 600
  backoffLimit: 50
  template:
    spec:
      containers:
        - name: wait
          image: curlimages/curl:8.5.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              until curl -sk -o /dev/null https://pod-identity-webhook.kube-system.svc:8443; do
                echo "Waiting for pod-identity-webhook port 8443..."
                sleep 3
              done
              echo "pod-identity-webhook is ready."
      restartPolicy: OnFailure
