apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3s-oci-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Vinny1892/infra-iac.git
    targetRevision: master
    path: oci/tenancy/regulus/us_ashburn_1/applications/k3s/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
