apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-lb-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://aws.github.io/eks-charts
      chart: aws-load-balancer-controller
      targetRevision: 3.1.0
      helm:
        valueFiles:
          - $values/aws/accounts/personal/us_east_1/applications/k3s/argocd/values/aws-lb-controller.yaml
    - repoURL: https://github.com/Vinny1892/infra-iac.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
