apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pod-identity-webhook
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://jkroepke.github.io/helm-charts
    chart: amazon-eks-pod-identity-webhook
    targetRevision: 2.6.0
    helm:
      valuesObject:
        fullnameOverride: pod-identity-webhook
        podAnnotations:
          eks.amazonaws.com/skip-pod-identity-webhook: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
