apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webhook-readiness-gate
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Vinny1892/infra-iac.git
    targetRevision: master
    path: aws/accounts/personal/us_east_1/applications/k3s/argocd/manifests/webhook-gate
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
