apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-external-ip-patcher
  namespace: traefik
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-external-ip-patcher
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-external-ip-patcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-external-ip-patcher
subjects:
  - kind: ServiceAccount
    name: traefik-external-ip-patcher
    namespace: traefik
