clusterName: k3s
serviceAccount:
  create: true
  name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::036785638465:role/k3s-aws-lb-controller
vpcId: vpc-00b70b6f4d4dd913b
region: us-east-1
