service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

ports:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
  publishedService:
    enabled: true

logs:
  general:
    level: INFO
