#!/usr/bin/env bash
set -eu

# Copy K3s organism Terraform files into the test fixture directory,
# applying mock substitutions needed for offline testing.

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${REPO_ROOT}/organisms/aws/k3s/cluster"
DEST="${REPO_ROOT}/tests/fixtures/k3s_extracted"

mkdir -p "${DEST}"

# Remove legacy provider.tf generated by the old extract script (replaced by versions.tf)
rm -f "${DEST}/provider.tf"

# Copy organism files verbatim (versions, variables, outputs)
cp "${SRC}/versions.tf"  "${DEST}/versions.tf"
cp "${SRC}/variables.tf" "${DEST}/variables.tf"
cp "${SRC}/outputs.tf"   "${DEST}/outputs.tf"

# main.tf: replace data.aws_caller_identity with a variable so terraform
# plan works without real AWS credentials (the data source calls live STS).
sed \
  's|data "aws_caller_identity" "current" {}|variable "account_id" {\n  type    = string\n  default = "123456789012"\n}|' \
  "${SRC}/main.tf" \
  | sed 's/data\.aws_caller_identity\.current\.account_id/var.account_id/g' \
  > "${DEST}/main.tf"

# Mock AWS provider override for testing (no real credentials needed)
cat > "${DEST}/provider_override.tf" <<'OVERRIDE'
provider "aws" {
  region                      = "us-east-1"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
  access_key                  = "mock"
  secret_key                  = "mock"
}

provider "tls" {}
OVERRIDE

# Symlink scripts directory (needed for templatefile() calls)
if [ -d "${SRC}/scripts" ]; then
  rm -f "${DEST}/scripts"
  ln -sf "${SRC}/scripts" "${DEST}/scripts"
fi

echo "K3s fixture extracted to ${DEST}"
