apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k3s-vinny-dev-br
  namespace: whoami
spec:
  secretName: k3s-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - k3s.vinny.dev.br
