apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  namespace: whoami
  annotations:
    external-dns.alpha.kubernetes.io/target: ${TRAEFIK_NLB_HOSTNAME}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`k3s.vinny.dev.br`) && PathPrefix(`/whoami`)
      kind: Rule
      services:
        - name: whoami
          port: 80
  tls:
    secretName: k3s-tls
